import streamlit as st
import pandas as pd
import numpy as np

# Load clustered dataset generated by notebook
df = pd.read_csv(
    "models/clustered_customers.csv"
)

st.title(
    "Hierarchical Clustering"
)

st.subheader(
    "Clustered Customer Data"
)

st.dataframe(df.head())

income = st.number_input(
    "Annual Income (k$)",
    min_value=1,
    max_value=200,
    value=50
)

score = st.number_input(
    "Spending Score (1-100)",
    min_value=1,
    max_value=100,
    value=50
)

if st.button("Find Similar Cluster"):

    distances = []

    for i in range(len(df)):

        d = np.sqrt(
            (
                df.iloc[i]["Annual Income (k$)"]
                - income
            )**2
            +
            (
                df.iloc[i]["Spending Score (1-100)"]
                - score
            )**2
        )

        distances.append(d)

    nearest_index = np.argmin(distances)

    cluster = df.iloc[
        nearest_index
    ]["Cluster"]

    st.success(
        f"Customer belongs to Cluster {int(cluster)}"
    )